from pathlib import Path
import pandas as pd

configfile: "config/config.yaml"

SAMPLE_TABLE = pd.read_csv(config["samples"], index_col="sample_id", sep="\t")
SAMPLE_TABLE.index = SAMPLE_TABLE.index.map(str)
SAMPLES = SAMPLE_TABLE.index.values

ORGANISMS = list(config['input']['sccg lists'].keys())
PHYSIOLOGY_DIMENSIONS = list(pd.read_table(config['input']['physiology data'], index_col="sample_id").columns)

print(ORGANISMS)

scratch_dir = Path(config["scratch directory"])
results_dir = Path(config["results directory"])
scratch_dict = {
    "genome_index": scratch_dir / "1_genomes" / "index",
    "gff_concat": scratch_dir / "1_genomes" / "concat.gff",
    "trimmed_reads": scratch_dir / "2_trimmed_reads", 
    "map_reads_paired": scratch_dir / "3_map_reads" / "paired",
    "map_reads_unpaired": scratch_dir / "3_map_reads" / "unpaired",
    "counting_dir": scratch_dir / "4_read_counts",
    "done_files": {
        "index": scratch_dir / "done_files" / "index.done"
    },
}

results_dict = {
    "organism_tables" : results_dir / "organism_count_tables",
    "zscores" : results_dir / "zscores",
    "omegas" : results_dir / "omegas",
    "pca_loadings" : results_dir / "pca" / "loadings",
    "pca_overlays" : results_dir / "pca" / "overlays",
    "regressions" : results_dir / "regressions",
    "gene_heatmaps" : results_dir / "gene_heatmaps",
    "physiology_heatmaps" : results_dir / "physiology_heatmaps",
}

rule all:
    input:
        expand(results_dict['pca_overlays'] / "{organism}" / "{organism}_{column}_pca_overlay.png",
            organism=ORGANISMS,
            column=PHYSIOLOGY_DIMENSIONS),
        expand(results_dict['regressions'] / "{organism}", organism=ORGANISMS),
        expand(results_dict['gene_heatmaps'] / "{organism}", organism=ORGANISMS),
        results_dict['physiology_heatmaps']

include: "rules/run_trim.smk"
include: "rules/ref_db_agg.smk"
include: "rules/map_reads_bowtie2.smk"
include: "rules/count_reads.smk"
include: "rules/analysis.smk"
