experiment name: "scope_gradients"

config: "config/config.yaml"
samples: "config/samples.tsv"

input: 
  reference genomes: /nfs/chisholmlab001/kve/2022_scope_gradients_HL_adaptation/inputs/reference_database/chosen_references
  reference genome lookup table: /nobackup1b/users/chisholmlab/img_proportal/data/lists/img_genome_lookup_table.txt
  cycog lookup table: /nobackup1b/users/chisholmlab/img_proportal/cycogs/CyCOGs-v6.0/cycog-genes.tsv
  reference annotations: /nfs/chisholmlab001/kve/2022_scope_gradients_HL_adaptation/inputs/reference_database/chosen_reference_gffs
  adapter file: /nfs/chisholmlab001/kve/genomic_resources/references/illumina/all_illumina_adapters.fa
  physiology data: /nfs/chisholmlab001/kve/2022_scope_gradients_HL_adaptation/inputs/physiology_data/nutrient_concentrations_seaflow.tsv
  sccg lists:
    Synechococcus: /nfs/chisholmlab001/kve/2022_scope_gradients_HL_adaptation/inputs/sccg_lists/syn_sccg.txt
    Prochlorococcus: /nfs/chisholmlab001/kve/2022_scope_gradients_HL_adaptation/inputs/sccg_lists/pro_sccg.txt
scratch directory: /nobackup1/chisholmlab/kve/2022_scope_gradients_HL_adaptation/scratch
results directory: /nfs/chisholmlab001/kve/2022_scope_gradients_HL_adaptation/results

counting features:
  minimum mapq quality: 0   # default is 10

read mapping:
  bowtie2 options string: "--no-unal --local -D 15 -R 2 -L 15 -N 1 --gbar 1 --mp 3"

omegas:
  Iron Medium:
    attributes:
      nutrient: Iron
      level: Medium
    genes:
      cirA: CyCOG_60002762
      expD: CyCOG_60002939
      febB: CyCOG_60002860
      fepB: CyCOG_60004907
      fepC: CyCOG_60002800
      tolQ: CyCOG_60003253
      tonB: CyCOG_60003177
  Iron Low:
    attributes:
      nutrient: Iron
      level: Low
    genes:
      crp1390: CyCOG_60001076
      PMM0804: CyCOG_60001007
      isiA: CyCOG_60000023
      dpsA: CyCOG_60002545
      fur: CyCOG_60000988
      futA: CyCOG_60000706
      futB: CyCOG_60000655
      futC: CyCOG_60000065
      isiB: CyCOG_60001112
  Phosphorus High:
    attributes:
      nutrient: Phosphorus
      level: High
    genes:
      phoA: CyCOG_60001947
      phoX: CyCOG_60002835
  Phosphorus Medium:
    attributes:
      nutrient: Phosphorus
      level: Medium
    genes:
      PMM707: CyCOG_60002002
      PMM721: CyCOG_60001743
      acr3: CyCOG_60002033
      arsR: CyCOG_60001390
      chrA: CyCOG_60001927
      gap1: CyCOG_60001385
      mfs: CyCOG_60001362
      phoB: CyCOG_60001922
      phoE: CyCOG_60000004
      phoR: CyCOG_60001747
      ptrA: CyCOG_60002396
      unkP1: CyCOG_60001755
      unkP2: CyCOG_60001748
      unkP3: CyCOG_60002204
      unkP4: CyCOG_60001942
      unkP5: CyCOG_60002088
  Phosphorus Low:
    attributes:
      nutrient: Phosphorus
      level: Low
    genes:
      PMM719: CyCOG_60000028
      PMM722: CyCOG_60001202
      phnD: CyCOG_60001141
      ppA: CyCOG_60000321
      ppK: CyCOG_60000178
      ppX: CyCOG_60000213
      pstA: CyCOG_60000929
      pstB: CyCOG_60001034
      pstC: CyCOG_60000999
      pstS: CyCOG_60000035
      sqdB: CyCOG_60000196
  Nitrogen High:
    attributes:
      nutrient: Nitrogen
      level: High
    genes:
      focA: CyCOG_60001803
      moaA: CyCOG_60001917
      moaB: CyCOG_60002248
      moaD: CyCOG_60001938
      moaE: CyCOG_60002268
      moeA: CyCOG_60002220
      moaC: CyCOG_60001901
      mobA: CyCOG_60003929
      napA: CyCOG_60001886
      narB: CyCOG_60001877
  Nitrogen Medium:
    attributes:
      nutrient: Nitrogen
      level: Medium
    genes:
      tauE: CyCOG_60003433
      cynA: CyCOG_60003114
      cynS: CyCOG_60001979
      nirA: CyCOG_60002024
      unkN1: CyCOG_60001787
      unkN2: CyCOG_60001931
      ureA: CyCOG_60001326
      ureB: CyCOG_60001317
      ureC: CyCOG_60001262
      ureD: CyCOG_60001340
      ureE: CyCOG_60001355
      ureF: CyCOG_60001331
      ureG: CyCOG_60001304
      urtA: CyCOG_60001296
  Nitrogen Low:
    attributes:
      nutrient: Nitrogen
      level: Low
    genes:
      dadA: CyCOG_60000244
      amt1: CyCOG_60000113
      carA: CyCOG_60001170
      carB: CyCOG_60000461
      gdhA: CyCOG_60003974
      glnA: CyCOG_60000563
      glnB: CyCOG_60000594
      glsF: CyCOG_60000039
      nadB: CyCOG_60000364
      ntcA: CyCOG_60000127
      pipX: CyCOG_60000819
      speA: CyCOG_60000095
      speB: CyCOG_60000436
      amtB: CyCOG_60003296
      thiO: CyCOG_60000080

nutrient regressions:
  Iron:
    - Fe_nM
  Phosphorus:
    - PO4_uM
    - TP_uM
    - TOP_uM
  Nitrogen:
    - NO3_NO2_uM
    - TN_uM
    - TON_uM
    - NO2_uM
    - NH4_uM
    - N_P_Ratio
  
# SiO4_uM
# TOC_uM
# Fe_nM
# Zn_nM
# Cd_pM
# Ni_nM
# Cu_nM
# Pb_pM
# Mn_nM
# Co_pM
# UnderwayTermperature_degC
# UnderwaySalnity_PSU