experiment_name: "2022_scope_gradients_HL_adaptation"

config: "config/config.yaml"
samples: "config/samples.tsv"

input: 
  internal_standard_ref: /nfs/chisholmlab001/kve/2022_scope_gradients_HL_adaptation/inputs/internal_standard_ref/thermus_thermophilus_ref.fasta
  kaiju_db_index: /nobackup1/chisholmlab/databases_kve/MARMICRODB/MARMICRODB.fmi
  kaiju_db_nodes: /nobackup1/chisholmlab/databases_kve/MARMICRODB/nodes.dmp
  kaiju_db_names: /nobackup1/chisholmlab/databases_kve/MARMICRODB/names.dmp
  cycog_db_index: /nobackup1b/users/chisholmlab/databases_kve/CyCOG6/CyCOG6_clean.fmi
  cycog_db_nodes: /nobackup1/chisholmlab/databases_kve/MARMICRODB/nodes.dmp
  adapter_file: /nfs/chisholmlab001/kve/genomic_resources/references/illumina/all_illumina_adapters.fa
  genes_of_interest: /nfs/chisholmlab001/kve/2022_scope_gradients_HL_adaptation/inputs/genes_of_interest/UstickLarson_stress_genes.fasta
scratch_dir: /nobackup1/chisholmlab/kve/2022_scope_gradients_HL_adaptation/scratch
results: /nfs/chisholmlab001/kve/2022_scope_gradients_HL_adaptation/results

internal_standard_taxa: "Thermus_thermophilus"

taxons_of_interst:
  Prochlorococcus: "Cyanobacteria; Synechococcales; Prochloraceae; Prochlorococcus;"
  Synechococcus: "Cyanobacteria; Synechococcales; Synechococcaceae;"
  Thermus_thermophilus: "Deinococci; Thermales; Thermaceae; Thermus;"
  ProHighLight: "Prochlorococcus; Prochlorococus clade HL;"
  ProHLI: "Prochlorococcus; Prochlorococus clade HL; Prochlorococus subclade HLI;"
  ProHLII: "Prochlorococcus; Prochlorococus clade HL; Prochlorococus subclade HLII;"
  ProHLIII_HLIV: "Prochlorococcus; Prochlorococus clade HL; Prochlorococus subclade HLIII.IV;"
  ProHLVI: "Prochlorococcus; Prochlorococus clade HL; Prochlorococus subclade HLVI;"
  ProLowLight: "Prochlorococcus; Prochlorococus clade LL;"
  ProLLI: "Prochlorococcus; Prochlorococus clade LL; Prochlorococus subclade LLI;"
  ProLLII_LLIII: "Prochlorococcus; Prochlorococus clade LL; Prochlorococus subclade LLII.III;"
  ProLLII: "Prochlorococcus; Prochlorococus clade LL; Prochlorococus subclade LLII.III; Prochlorococus subsubclade LLII;"
  ProLLIII: "Prochlorococcus; Prochlorococus clade LL; Prochlorococus subclade LLII.III; Prochlorococus subsubclade LLIII;"
  ProLLIV: "Prochlorococcus; Prochlorococus clade LL; Prochlorococus subclade LLIV;"
  ProLLVII: "Prochlorococcus; Prochlorococus clade LL; Prochlorococus subclade LLVII;"
  ProLLVIIa: "Prochlorococcus; Prochlorococus clade LL; Prochlorococus subclade LLVII; Prochlorococus subsubclade LLVIIa;"
  ProLLVIIb: "Prochlorococcus; Prochlorococus clade LL; Prochlorococus subclade LLVII; Prochlorococus subsubclade LLVIIb;"
  ProLLVIIc: "Prochlorococcus; Prochlorococus clade LL; Prochlorococus subclade LLVII; Prochlorococus subsubclade LLVIIc;"
  ProLLVIId: "Prochlorococcus; Prochlorococus clade LL; Prochlorococus subclade LLVII; Prochlorococus subsubclade LLVIId;"
  ProLLVIIe: "Prochlorococcus; Prochlorococus clade LL; Prochlorococus subclade LLVII; Prochlorococus subsubclade LLVIIe;"
  ProLLVIII: "Prochlorococcus; Prochlorococus clade LL; Prochlorococus subclade MIT1223;"
  Syn5p1: "Synechococcus clade 5.1;"
  Syn5p2: "Synechococcus clade 5.2;"
  Syn5p3: "Synechococcus clade 5.3;"
  Syn5p1A: "Synechococcus subclade 5.1A;"
  Syn5p1B: "Synechococcus subclade 5.1B;"
  SynClade_I: "Synechococcus subsubclade I;"
  SynClade_II: "Synechococcus subsubclade II;"
  SynClade_III: "Synechococcus subsubclade III;"
  SynClade_IV: "Synechococcus subsubclade IV;"
  SynClade_UC_A: "Synechococcus subsubclade UC-A;"
  SynClade_VIII_IX: "Synechococcus subsubclade VIII.IX;"
  SynClade_V_VI_VII: "Synechococcus subsubclade V.VI.VII;"
  SynClade_WPCI: "Synechococcus subsubclade WPCI;"

CyCOG_taxa_interest:
  - ProHighLight

CyCOG_assignments:
  cirA: "CyCOG_60002762"
  expD: "CyCOG_60002939"
  febB: "CyCOG_60002860"
  fepB: "CyCOG_60004907"
  fepC: "CyCOG_60002800"
  tolQ: "CyCOG_60003253"
  tonB: "CyCOG_60003177"
  crp1390: "CyCOG_60001076"
  PMM0804: "CyCOG_60001007"
  isiA: "CyCOG_60000023"
  dpsA: "CyCOG_60002545"
  fur: "CyCOG_60000988"
  futA: "CyCOG_60000706"
  futB: "CyCOG_60000655"
  futC: "CyCOG_60000065"
  isiB: "CyCOG_60001112"
  phoA: "CyCOG_60001947"
  phoX: "CyCOG_60002835"
  PMM707: "CyCOG_60002002"
  PMM721: "CyCOG_60001743"
  acr3: "CyCOG_60002033"
  arsR: "CyCOG_60001390"
  chrA: "CyCOG_60001927"
  gap1: "CyCOG_60001385"
  mfs: "CyCOG_60001362"
  phoB: "CyCOG_60001922"
  phoE: "CyCOG_60000004"
  phoR: "CyCOG_60001747"
  ptrA: "CyCOG_60002396"
  unkP1: "CyCOG_60001755"
  unkP2: "CyCOG_60001748"
  unkP3: "CyCOG_60002204"
  unkP4: "CyCOG_60001942"
  unkP5: "CyCOG_60002088"
  PMM719: "CyCOG_60000028"
  PMM722: "CyCOG_60001202"
  phnD: "CyCOG_60001141"
  ppA: "CyCOG_60000321"
  ppK: "CyCOG_60000178"
  ppX: "CyCOG_60000213"
  pstA: "CyCOG_60000929"
  pstB: "CyCOG_60001034"
  pstC: "CyCOG_60000999"
  pstS: "CyCOG_60000035"
  sqdB: "CyCOG_60000196"
  focA: "CyCOG_60001803"
  moaA: "CyCOG_60001917"
  moaB: "CyCOG_60002248"
  moaD: "CyCOG_60001938"
  moaE: "CyCOG_60002268"
  moeA: "CyCOG_60002220"
  moaC: "CyCOG_60001901"
  mobA: "CyCOG_60003929"
  napA: "CyCOG_60001886"
  narB: "CyCOG_60001877"
  tauE: "CyCOG_60003433"
  cynA: "CyCOG_60003114"
  cynS: "CyCOG_60001979"
  nirA: "CyCOG_60002024"
  unkN1: "CyCOG_60001787"
  unkN2: "CyCOG_60001931"
  ureA: "CyCOG_60001326"
  ureB: "CyCOG_60001317"
  ureC: "CyCOG_60001262"
  ureD: "CyCOG_60001340"
  ureE: "CyCOG_60001355"
  ureF: "CyCOG_60001331"
  ureG: "CyCOG_60001304"
  urtA: "CyCOG_60001296"
  dadA: "CyCOG_60000244"
  amt1: "CyCOG_60000113"
  carA: "CyCOG_60001170"
  carB: "CyCOG_60000461"
  gdhA: "CyCOG_60003974"
  glnA: "CyCOG_60000563"
  glnB: "CyCOG_60000594"
  glsF: "CyCOG_60000039"
  nadB: "CyCOG_60000364"
  ntcA: "CyCOG_60000127"
  pipX: "CyCOG_60000819"
  speA: "CyCOG_60000095"
  speB: "CyCOG_60000436"
  amtB: "CyCOG_60003296"
  thiO: "CyCOG_60000080"
